apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-llm-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-llm-vm
    spec:
      architecture: amd64
      domain:
        machine:
          type: q35
        cpu:
          cores: 4
        resources:
          requests:
            memory: 8Gi
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - name: cloudinit
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        persistentVolumeClaim:
          claimName: ubuntu22-disk
      - name: cloudinit
        cloudInitNoCloud:
          userData: |
            #cloud-config
            users:
              - name: ubuntu
                sudo: ALL=(ALL) NOPASSWD:ALL
                shell: /bin/bash
                ssh-authorized-keys:
                  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDdJ6jvxp2pGJQ4aGr99NXywQD0Q8tS8G/JYo1NNkqdO 
            package_update: true
            package_upgrade: true
            packages:
              - qemu-guest-agent
              - curl
              - git
              - htop
